
@baseurl = http://127.0.0.1:3000
@id = 1

### GET /todos
GET {{baseurl}}/todos

### POST /todos
POST {{baseurl}}/todos
content-type: application/json

{
    "subject": "Test"
}

### PUT /todos/:id
PUT {{baseurl}}/todos/{{id}}
content-type: application/json

{
    "subject": "Test2",
    "completed": true,
    "status": 5
}


### DELETE /todos/:id
DELETE {{baseurl}}/todos/{{id}}
